package com.vadeen.neat.gui.panel;

import javax.swing.*;
import java.awt.*;

public class MainPanel {

    private JPanel contentPane;

    private JPanel controlPanelWrapper;
    private JPanel statsPanelWrapper;
    private JPanel visualizationPanelWrapper;

    public static JPanel create(JPanel controlPanel, JPanel statsPanel, JPanel visualizationPanel) {
        return new MainPanel(controlPanel, statsPanel, visualizationPanel).contentPane;
    }

    private MainPanel(JPanel controlPanel, JPanel statsPanel, JPanel visualizationPanel) {
        $$$setupUI$$$();
        this.controlPanelWrapper.add(controlPanel);
        this.statsPanelWrapper.add(statsPanel);
        this.visualizationPanelWrapper.add(visualizationPanel);
    }

    private void createUIComponents() {
        controlPanelWrapper = new JPanel();
        statsPanelWrapper = new JPanel();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentPane = new JPanel();
        contentPane.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JSplitPane splitPane1 = new JSplitPane();
        splitPane1.setDividerLocation(800);
        contentPane.add(splitPane1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(200, 200), null, 0, false));
        splitPane1.setRightComponent(statsPanelWrapper);
        visualizationPanelWrapper = new JPanel();
        visualizationPanelWrapper.setLayout(new GridBagLayout());
        splitPane1.setLeftComponent(visualizationPanelWrapper);
        contentPane.add(controlPanelWrapper, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTHWEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }
}
